# 服务器配置
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

# Spring配置
spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/todo_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&connectTimeout=5000&socketTimeout=30000
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
  # JPA配置
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      # 自动更新数据库表结构
      ddl-auto: update
    # 显示SQL语句
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

# 日志配置
logging:
  level:
    root: INFO
    com.example.todolist: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE